spring:
  cloud:
    azure:
      cosmos:
        database: ToDoList
        populate-query-metrics: true
        endpoint: https://springbasic.documents.azure.com:443/
        key: YFO89SYY2QIcVJ3zAyid55TcJmeMM4du8EVDmAbmnl4GK8o2ztITyVfVUHkTB8JIBj3KQGu1YmutACDbeV2pfA==
